Add z.describe support
astahmer/openapi-zod-client pull request #143
Opened 2023-05-29 19:38 UTC by dosco

2023-05-29 19:49 UTC, astahmer requested changes

2023-05-29 19:49 UTC, astahmer commented on lib/src/getZodiosEndpointDefinitionList.ts
> +                    paramSchema = { ...paramSchema, description };
just set the paramSchema property, no need to spread there I think

2023-05-29 19:50 UTC, astahmer commented
can you add a specific test for this & add a [changeset](https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md) so I can merge it ?

2023-05-30 03:27 UTC, dosco commented
I added a test but now I see that over 20 tests fail cause now the descriptions cause the zod to have a `describe()` and the tests are purely string matching on large text blobs. Do you have a suggestion short of me having to go update all these tests?

2023-05-30 03:33 UTC, dosco commented
Also I've added a change set (not familiar with this) using `npx changeset add` and the test.

2023-05-30 07:32 UTC, astahmer commented
> 

you can try to update the tests using vitest (I think you just need to hit the "U" key) and check that everything looks correct, then you should be good to go !

2023-05-30 18:19 UTC, dosco commented
> > 
> 
> you can try to update the tests using vitest (I think you just need to hit the "U" key) and check that everything looks correct, then you should be good to go !

Thanks, I was new to most of tooling in this repo, like vitest, pnpm, preconstruct, etc so good to learn some new stuff. I tried everything however I can't figure out why `samples.test.ts` and `callback-example.yaml` is failing.  All other tests are passing.

2023-05-30 19:44 UTC, astahmer commented
![Screenshot 2023-05-30 at 21 44 05](https://github.com/astahmer/openapi-zod-client/assets/47224540/72e0ccc9-cc40-42ab-bafe-45ea534fc85f)

looking at the CI, there seems to be an issue with the pnpm-lock file, could you try deleting it & running `pnpm i` afterwards ? it should fix it and then i'll be able to see the failing tests

2023-05-31 00:07 UTC, dosco commented
I tried that I don't get any "fixed" file I just get the same one back so nothing to commit. I ended up manually reverting the file to the version in your repo (Hope that works). Whatever breaking change this was it was caused by a simple `pnpm i` I recommend  just using `npm` which is way more used and tested.

https://github.com/dosco/openapi-zod-client/commit/a511340c518cb20d8c4baa7e22847c72314f097e#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bb

2023-05-31 21:30 UTC, astahmer commented
I made the appropriate changes here, i'll close this one and merge the new one
https://github.com/astahmer/openapi-zod-client/pull/148

2023-05-31 21:30 UTC, closed without merging